### PR TITLE
🧹 Try to update os provider to latest

### LINKED ISSUE #149: plugin cannot gather the full report
**Describe the bug**
Different error messages while running the plugin:
```
failed to handshake
```

```
could not gather the full report
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**
This shouldn't error.

**Desktop (please complete the following information):**

- packer-plugin-cnspec v9.2.4

**Additional context**
It works with packer-plugin-cnspec v9.2.2.

### PR DESCRIPTION
**Pull request by czunker**
Fixes #149

### CODE REVIEW

File: provisioner/provisioner.go [hunk 1]
```diff
@@ -598,3 +600,37 @@ func (p *Provisioner) executeCnspec(ui packer.Ui, comm packer.Communicator) erro
...
+func updateOsProvider(ui packer.Ui) {
+	allProviders, err := providers.ListActive()
+	if err != nil {
+		ui.Error(err.Error())
+		ui.Message("failed to list providers, not going to update cnspec os provider")
+		return
+	}
+	outdated := false
+	for _, provider := range allProviders {
+		if provider.Name == "os" {
```
Comment (imilchev) [inline provisioner/provisioner.go:613]: is it just the os provider that we are interested in? is it possible that other providers are also used by the packer plugin? We do have types in OS that are defined in network, for example... Shouldn't this be just the same function as the one updating the providers in cnspec?

Comment (czunker) [reply provisioner/provisioner.go:613]: The network provider is a good catch. Didn't think about this one. Yes, then we can use the same code as for the cnspec PR.

**Review by imilchev — APPROVED** [review]
